disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "OURCE"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "light.svg"
secondaryLogo = "dark.svg"
description = "Enabling hands to shape their own future."
